package identies;
// Generated Oct 13, 2016 12:38:13 AM by Hibernate Tools 4.3.1



/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private String taikhoan;
     private String matkhau;
     private String hoten;
     private String email;
     private String role;

    public Khachhang() {
    }

	
    public Khachhang(String taikhoan) {
        this.taikhoan = taikhoan;
    }
    public Khachhang(String taikhoan, String matkhau, String hoten, String email, String role) {
       this.taikhoan = taikhoan;
       this.matkhau = matkhau;
       this.hoten = hoten;
       this.email = email;
       this.role = role;
    }
   
    public String getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(String taikhoan) {
        this.taikhoan = taikhoan;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


